# https://travis-ci.org/burgerbecky/makeprojects
# Docs for Travis https://docs.travis-ci.com/

# Python testing
language: python

# Cache the python pip and environment folders
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

# Only track the master branch, don't process pull requests
branches:
  only:
    - master

# Allow apt-update
addons:
  apt:
    update: true

# Test on Linux and MacOS versions of Python
# Windows is tested at Olde Skuul

matrix:
  include:
  # Windows builds (Not supported for python on 3/19/2019)
  #- os: windows
  #  dist: 1803-containers
  #  python: '2.7'
  #  env: TOXENV=py27

  # Linux builds
  # Linux versions
  # precise = 12.04
  # trusty = 14.04
  # xenial = 16.04
  # bionic = 18.04
  - os: linux
    dist: xenial
    sudo: false
    python: '2.7'
    env: TOXENV=py27

  - os: linux
    dist: xenial
    sudo: false
    python: '3.4'
    env: TOXENV=py34

  - os: linux
    dist: xenial
    sudo: false
    python: '3.5'
    env: TOXENV=py35

  - os: linux
    dist: xenial
    sudo: false
    python: '3.6'
    env: TOXENV=py36

  - os: linux
    dist: xenial
    sudo: false
    python: '3.7-dev'
    env: TOXENV=py37

  - os: linux
    dist: trusty
    sudo: false
    python: 'pypy'
    env: TOXENV=pypy

  - os: linux
    dist: trusty
    sudo: false
    python: 'pypy3'
    env: TOXENV=pypy3

  - os: linux
    dist: trusty
    sudo: false
    python: 'pypy-5.4'
    env: TOXENV=pypy

  # macOS builds
  - os: osx
    language: objective-c
    env:
      - TOXENV=py27 
      - PYENV_VERSION=2.7.15
  - os: osx
    language: objective-c
    env: 
      - TOXENV=py34
      - PYENV_VERSION=3.4.8
  - os: osx
    language: objective-c
    env: 
      - TOXENV=py35
      - PYENV_VERSION=3.5.5
  - os: osx
    language: objective-c
    env: 
      - TOXENV=py36
      - PYENV_VERSION=3.6.5
  - os: osx
    language: objective-c
    env: 
      - TOXENV=py37
      - PYENV_VERSION=3.7-dev

# Before installing python packages, make sure python is present
before_install:
  # macOS needs some pyenv love.
  - pyenv versions
  - pyenv install --list
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install -s $PYENV_VERSION; fi
  - python --version
  - uname -a
  - echo $PATH
  # Debug spew for linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then readlink -f `which python`; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls $(dirname $(readlink -f `which python`)); fi
  
# Install python packages needed for this test and get versions for log
install:
  - pip install burger
  - pip install tox-travis wheel codecov coverage funcsigs
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

# Tox does all the work
script:
  - tox

# Output the errors, if any
after_failure:
  - more temp/tox/log/* | cat
  - more temp/tox/*/log/* | cat

# Send a pass/fail to us
notifications:
  slack:
    rooms:
      secure: jsn83OekZv/QKLeUYivtG/R7A9wyNOjaNOj7a3pluwI8IEcL9wmsc7jNHVPLFYkAtcWcg8W5r0mE2Ewm2l2l5a6ZRoW9s7m9VCHdfWnRE7T7+YbdLNvpT8+pXdfPRD3eG1EULbk6ffUBphiM+1UCv4otkOPVXUCUvLQ8r0uLWg0gEsvf53wkxz90KqSC/c3Ta1ct7XLaRgPVTxwz48JY+RdSP2z/rrQmMq1xOQ2/40QdJZJ0thH+euuam2HaPCN9kwbdtGCQzdr4IvKD108yUR5bOfMTpTuJrNcRszUv5W1n4msbmH+VbNTgoxvLrvP5WcYtamlfsrs4trOSUopz/ENXtPCphst+frs2DNWbrBxutBTfwljDn4ay29YNT2L3c1Ml9PM9rdYg1kWOL4610CP80ZgK8tB7rzNslOMcCs7hV8uXSvYkVrRX8CXgF/xYSmBFr8uVtFF7/g9APITFNVvwSIVy9UjxhzEOnf4AcbEUTfQWiZBL+hVclNhTXDBYR3TRaRpY45kUOfGEyycMrwud7evqx/LGhrv9auQiZukto+A0Gu/LLac/BQ30jlmIsu5u8qa0iM6HZA3av+alHkH9rrG9SIOEP0Hq4tKyhMg3q/c5wxoq1co9T6Eeg9qQoy7Aa1MMH7rhQ9R3AST/dFU1CVyvnE8mNgQ1KfUzJ3c=
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: always
