blank_issues_enabled: false
contact_links:
  - name: Help and support
    url: https://github.com/burgerbecky/makeprojects/discussions
    about: Please use GitHub Discussions if you have questions or need help.
