# Name of this workflow
name: Makeprojects for Python

# Only process when a new version is pushed on master
on:
  push:
    branches:
      - "master"

jobs:
  "Run_Pytest":
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Here are all the operating systems and python versions to test on.
      matrix:
        name:
          - "ubuntu-20-py36"
          - "ubuntu-20-py37"
          - "ubuntu-20-py38"
          - "ubuntu-20-py39"
          - "ubuntu-20-py310"
          - "ubuntu-20-py311"
          - "ubuntu-20-py312"
          - "ubuntu-20-pypy2"
          - "ubuntu-20-pypy3"
          - "ubuntu-22-py37"
          - "ubuntu-22-py38"
          - "ubuntu-22-py39"
          - "ubuntu-22-py310"
          - "ubuntu-22-py311"
          - "ubuntu-22-py312"
          - "macos13-py36"
          - "macos13-py37"
          - "macos13-py38"
          - "macos13-py39"
          - "macos13-py310"
          - "macos13-py311"
          - "macos13-py312"
          - "macos13-pypy2"
          - "macos14-py38"
          - "macos14-py39"
          - "macos14-py310"
          - "macos14-py311"
          - "macos14-py312"
          - "windows-2019-py36"
          - "windows-2019-py37"
          - "windows-2019-py38"
          - "windows-2019-py39"
          - "windows-2019-py310"
          - "windows-2019-py311"
          - "windows-2019-py312"
          - "windows-2019-pypy2"
          - "windows-2019-pypy3"
          - "windows-2022-py36"
          - "windows-2022-py37"
          - "windows-2022-py38"
          - "windows-2022-py39"
          - "windows-2022-py310"
          - "windows-2022-py311"
          - "windows-2022-py312"
          - "windows-2022-pypy2"
        # Specific data for each version being built
        include:
          # Ubuntu 20
          - name: "ubuntu-20-py36"
            python: "3.6"
            os: "ubuntu-20.04"
            tox_env: "py36"
          - name: "ubuntu-20-py37"
            python: "3.7"
            os: "ubuntu-20.04"
            tox_env: "py37"
          - name: "ubuntu-20-py38"
            python: "3.8"
            os: "ubuntu-20.04"
            tox_env: "py38"
          - name: "ubuntu-20-py39"
            python: "3.9"
            os: "ubuntu-20.04"
            tox_env: "py39"
          - name: "ubuntu-20-py310"
            python: "3.10"
            os: "ubuntu-20.04"
            tox_env: "py310"
          - name: "ubuntu-20-py311"
            python: "3.11"
            os: "ubuntu-20.04"
            tox_env: "py311"
          - name: "ubuntu-20-py312"
            python: "3.12"
            os: "ubuntu-20.04"
            tox_env: "py312"
          - name: "ubuntu-20-pypy2"
            python: "pypy2"
            os: "ubuntu-20.04"
            tox_env: "pypy2"
          - name: "ubuntu-20-pypy3"
            python: "pypy3"
            os: "ubuntu-20.04"
            tox_env: "pypy3"
          # Ubuntu 22
          - name: "ubuntu-22-py37"
            python: "3.7"
            os: "ubuntu-22.04"
            tox_env: "py37"
          - name: "ubuntu-22-py38"
            python: "3.8"
            os: "ubuntu-22.04"
            tox_env: "py38"
          - name: "ubuntu-22-py39"
            python: "3.9"
            os: "ubuntu-22.04"
            tox_env: "py39"
          - name: "ubuntu-22-py310"
            python: "3.10"
            os: "ubuntu-22.04"
            tox_env: "py310"
          - name: "ubuntu-22-py311"
            python: "3.11"
            os: "ubuntu-22.04"
            tox_env: "py311"
          - name: "ubuntu-22-py312"
            python: "3.12"
            os: "ubuntu-22.04"
            tox_env: "py312"
          # MacOS 13
          - name: "macos13-py36"
            python: "3.6"
            os: "macos-13"
            tox_env: "py36"
          - name: "macos13-py37"
            python: "3.7"
            os: "macos-13"
            tox_env: "py37"
          - name: "macos13-py38"
            python: "3.8"
            os: "macos-13"
            tox_env: "py38"
          - name: "macos13-py39"
            python: "3.9"
            os: "macos-13"
            tox_env: "py39"
          - name: "macos13-py310"
            python: "3.10"
            os: "macos-13"
            tox_env: "py310"
          - name: "macos13-py311"
            python: "3.11"
            os: "macos-13"
            tox_env: "py311"
          - name: "macos13-py312"
            python: "3.12"
            os: "macos-13"
            tox_env: "py312"
          - name: "macos13-pypy2"
            python: "pypy2"
            os: "macos-13"
            tox_env: "pypy2"
          # MacOS 14
          - name: "macos14-py38"
            python: "3.8"
            os: "macos-14"
            tox_env: "py38"
          - name: "macos14-py39"
            python: "3.9"
            os: "macos-14"
            tox_env: "py39"
          - name: "macos14-py310"
            python: "3.10"
            os: "macos-14"
            tox_env: "py310"
          - name: "macos14-py311"
            python: "3.11"
            os: "macos-14"
            tox_env: "py311"
          - name: "macos14-py312"
            python: "3.12"
            os: "macos-14"
            tox_env: "py312"
          # Windows 2019 Server
          - name: "windows-2019-py36"
            python: "3.6"
            os: "windows-2019"
            tox_env: "py36"
          - name: "windows-2019-py37"
            python: "3.7"
            os: "windows-2019"
            tox_env: "py37"
          - name: "windows-2019-py38"
            python: "3.8"
            os: "windows-2019"
            tox_env: "py38"
          - name: "windows-2019-py39"
            python: "3.9"
            os: "windows-2019"
            tox_env: "py39"
          - name: "windows-2019-py310"
            python: "3.10"
            os: "windows-2019"
            tox_env: "py310"
          - name: "windows-2019-py311"
            python: "3.11"
            os: "windows-2019"
            tox_env: "py311"
          - name: "windows-2019-py312"
            python: "3.12"
            os: "windows-2019"
            tox_env: "py312"
          - name: "windows-2019-pypy2"
            python: "pypy2"
            os: "windows-2019"
            tox_env: "pypy2"
          - name: "windows-2019-pypy3"
            python: "pypy3"
            os: "windows-2019"
            tox_env: "pypy3"
          # Windows 2022 Server
          - name: "windows-2022-py36"
            python: "3.6"
            os: "windows-2022"
            tox_env: "py36"
          - name: "windows-2022-py37"
            python: "3.7"
            os: "windows-2022"
            tox_env: "py37"
          - name: "windows-2022-py38"
            python: "3.8"
            os: "windows-2022"
            tox_env: "py38"
          - name: "windows-2022-py39"
            python: "3.9"
            os: "windows-2022"
            tox_env: "py39"
          - name: "windows-2022-py310"
            python: "3.10"
            os: "windows-2022"
            tox_env: "py310"
          - name: "windows-2022-py311"
            python: "3.11"
            os: "windows-2022"
            tox_env: "py311"
          - name: "windows-2022-py312"
            python: "3.12"
            os: "windows-2022"
            tox_env: "py312"
          - name: "windows-2022-pypy2"
            python: "pypy2"
            os: "windows-2022"
            tox_env: "pypy2"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install pytest wslwinreg burger
      - name: Test with pytest
        run: |
          python -V
          pytest
